"""add tasks

Revision ID: 7cabcdb7d918
Revises: d21134a288e0
Create Date: 2020-05-06 15:50:26.938521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cabcdb7d918'
down_revision = 'd21134a288e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('task', 'desc')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('task', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task', 'description')
    # ### end Alembic commands ###
